version: '3'
services:
  geth:
    container_name: geth.local
    build:
      context: "."
      dockerfile: "docker/geth/Dockerfile"
    ports: 
      - "8545:8545"
      - "30303:30303"
    volumes:
      # - "./docker/geth/data:/home/geth/data"
      - "./docker/geth/config:/home/geth/config"
      - "./docker/keystore:/home/geth/keystore"
    command: --datadir /home/geth/data --keystore /home/geth/keystore --networkid 99 --allow-insecure-unlock --unlock 0x1bb90cde8a032cb4963813a5b4db4981afa5b9c6,0xfadad77b3a7e5a84a1f7ded081e785585d4ffaf3,0x3980aa37f838bec2e457445d943feb3af98ff036 --networkid 99 --lightkdf --nodiscover --maxpeers=0 --port=0 --nousb --ipcdisable --mine --miner.threads 1 --miner.etherbase 0x1bb90cde8a032cb4963813a5b4db4981afa5b9c6 --http --http.port 8545 --http.api admin,personal,eth,miner,debug,txpool,net,web3 --http.addr 0.0.0.0 --http.corsdomain * --http.vhosts * --rpc.allow-unprotected-txs --password=/home/geth/keystore/password
  # deployer:
  #   build:
  #     context: "."
  #     dockerfile: "docker/deployer/Dockerfile"
  #   volumes:
  #     - "./docker/geth/bin/:/root/bin"
  #   command: ["median-deploy", "BATUSD", "BTCUSD", "ETHUSD", "KNCUSD", "MANAUSD", "0x1bb90cde8a032cb4963813a5b4db4981afa5b9c6", "0x3980aa37f838bec2e457445d943feb3af98ff036"]
  ssb_client_feed:
    depends_on:
      - ssb_server_feed
    build:
      context: "."
      dockerfile: "docker/ssb-server/Dockerfile"
    volumes:
      - "./docker/ssb-server/config/client_feed.json:/root/.ssb/config"
      - "./docker/ssb-server/config/secret_feed:/root/.ssb/secret"
    command: ["/bin/bash"]
  ssb_client_relayer:
    depends_on:
      - ssb_server_relayer
    build:
      context: "."
      dockerfile: "docker/ssb-server/Dockerfile"
    volumes:
      - "./docker/ssb-server/config/client_relayer.json:/root/.ssb/config"
      - "./docker/ssb-server/config/secret_relayer:/root/.ssb/secret"
    command: ["/bin/bash"]
  ssb_server_feed:
    container_name: ssb-feed.local
    build:
      context: "."
      dockerfile: "docker/ssb-server/Dockerfile"
    ports:
      - "8008:8008"
    volumes:
      - "./docker/ssb-server/config/server_feed.json:/root/.ssb/config"
      - "./docker/ssb-server/config/secret_feed:/root/.ssb/secret"
  ssb_server_relayer:
    container_name: ssb-relayer.local
    build:
      context: "."
      dockerfile: "docker/ssb-server/Dockerfile"
    expose:
      - 8009
    ports:
      - "8009:8009"
    volumes:
      - "./docker/ssb-server/config/server_relayer.json:/root/.ssb/config"
      - "./docker/ssb-server/config/secret_relayer:/root/.ssb/secret"
  omnia_feed:
    depends_on:
      - spire_feed
    image: ghcr.io/chronicleprotocol/omnia_dev:latest
    volumes:
      - "./lib:/home/omnia/lib"
      - "./test:/home/omnia/test"
      - "./docker/omnia/config/feed.conf:/home/omnia/config/feed.conf"
      - "./docker/spire/config/client_feed.json:/home/omnia/spire.json"
      - "./docker/ssb-server/config/client_feed.json:/home/omnia/.ssb/config"
    environment:
      OMNIA_CONFIG: /home/omnia/config/feed.conf
  omnia_relay:
    depends_on:
      - spire_relay
      - geth
    image: ghcr.io/chronicleprotocol/omnia_dev:latest
    volumes:
      - "./lib:/home/omnia/lib"
      - "./test:/home/omnia/test"
      - "./docker/omnia/config/relay.conf:/home/omnia/config/relay.conf"
      - "./docker/spire/config/client_relay.json:/home/omnia/spire.json"
      - "./docker/ssb-server/config/client_feed.json:/home/omnia/.ssb/config"
    environment:
      OMNIA_CONFIG: /home/omnia/config/relay.conf
  spire_feed:
    image: ghcr.io/chronicleprotocol/spire:latest
    container_name: spire_feed.local
    expose:
      - "8000"
    ports:
      - "9100:9100"
    command: ["-c", "/root/spire.json", "agent"]
    volumes:
      - "./docker/keystore:/root/keystore"
      - "./docker/spire/config/agent_feed.json:/root/spire.json"
  spire_relay:
    image: ghcr.io/chronicleprotocol/spire:latest
    container_name: spire_relay.local
    expose:
      - "8000"
    ports:
      - "9101:9100"
    command: ["-c", "/root/spire.json", "agent"]
    volumes:
      - "./docker/keystore:/root/keystore"
      - "./docker/spire/config/agent_relay.json:/root/spire.json"
