#!/usr/bin/env bash
set -eo pipefail
if [[ -n $OMNIA_DEBUG ]]; then set -x; fi

LIB_PATH="$(cd "${0%/*/*}" && pwd)/lib"
source "$LIB_PATH/log.sh"

# log calls to seth
verbose --list "seth call" "$@"

exec seth "$@"