#!/usr/bin/env bash
set -eo pipefail
if [[ -n $OMNIA_DEBUG ]]; then set -x; fi

echo "out - OMNIA_DEBUG:$OMNIA_DEBUG;OMNIA_CONFIG:$OMNIA_CONFIG"
(cd "$(cd "${0%/*/*}" && pwd)/lib"
	source ./log.sh

  echo "in - OMNIA_DEBUG:$OMNIA_DEBUG;OMNIA_CONFIG:$OMNIA_CONFIG"
	verbose --list "seth call" "$@"

	exec seth "$@"
)