name: Build & Push Production SSB Docker Images
on:
  workflow_dispatch: # Allow manual trigger
  push: # Build & release on tags
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker SSB Server metadata
        id: metassb
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/chronicleprotocol/ssb_server
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish SSB Server Image to Github Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/ssb-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metassb.outputs.tags }}
          labels: ${{ steps.metassb.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max