name: Omnia Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: .github/docker-compose-unit-tests.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Tests
        run: docker-compose -f $COMPOSE_FILE run --rm omnia_unit_tests
