name: Omnia Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: .github/docker-compose-unit-tests.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PreBuild Omnia images (Remove after PR merge)
        run: docker build -t ghcr.io/chronicleprotocol/omnia:dev -f Dockerfile .
      - name: Run Unit Tests
        run: docker-compose -f $COMPOSE_FILE run --rm omnia_unit_tests

  test-e2e:
    name: E2E tests
    needs: unit-test
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: .github/docker-compose-e2e-tests.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PreBuild Omnia images (Remove after PR merge)
        run: docker build -t ghcr.io/chronicleprotocol/omnia:dev -f Dockerfile .
      - name: Building Omnia e2e image
        run: docker-compose -f $COMPOSE_FILE build omnia_e2e
      - name: Running Omnia Feed E2E tests
        run: docker-compose -f $COMPOSE_FILE run --rm omnia_e2e go test -v -parallel 1 -cpu 1 ./feed
      - name: Running Omnia Relay E2E tests
        run: docker-compose -f $COMPOSE_FILE run --rm omnia_e2e go test -v -parallel 1 -cpu 1 ./relay
