name: Omnia Unit tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: .github/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Build and Publish Omnia Image to Github Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./docker/omnia/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/chronicleprotocol/omnia_dev:testing

      - name: Run Unit Tests
        run: docker-compose run --rm omnia